
CREATE TABLE roles (
                       id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       name VARCHAR(255) NOT NULL,
                       CONSTRAINT uq_roles_name UNIQUE (name)
);

CREATE TABLE fermentation_types (
                                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                    name VARCHAR(255) NOT NULL,
                                    CONSTRAINT uq_fermentation_types_name UNIQUE (name)
);

CREATE TABLE activity_types (
                                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                name VARCHAR(255) NOT NULL,
                                CONSTRAINT uq_activity_types_name UNIQUE (name)
);


CREATE TABLE beers (
                       id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       name VARCHAR(255) NOT NULL,

                       price DOUBLE PRECISION NOT NULL,
                       volume DOUBLE PRECISION NOT NULL,

                       fermentation_type BIGINT NOT NULL REFERENCES fermentation_types(id),

                       srm BIGINT NOT NULL,
                       ibu BIGINT NOT NULL,
                       abv BIGINT NOT NULL,
                       og  BIGINT NOT NULL,

                       country VARCHAR(255),
                       image_path VARCHAR(1024),

                       average_rating DOUBLE PRECISION,

                       last_updated TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE users (
                       id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

                       username VARCHAR(255) NOT NULL UNIQUE,
                       password VARCHAR(255) NOT NULL,

                       email VARCHAR(255),
                       first_name VARCHAR(255),
                       last_name VARCHAR(255),
                       country VARCHAR(255),
                       preferred_language VARCHAR(255),

                       roles_id BIGINT NOT NULL REFERENCES roles(id),

                       avatar_path VARCHAR(1024),
                       created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE reviews (
                         id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

                         rating REAL NOT NULL,

                         comment TEXT NOT NULL,

                         created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

                         beer_reviewed_id BIGINT NOT NULL REFERENCES beers(id),

                         CONSTRAINT chk_reviews_rating_range CHECK (rating >= 0 AND rating <= 5)
);

CREATE TABLE activities (
                            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

                            user_id BIGINT NOT NULL REFERENCES users(id),

                            type_id BIGINT NOT NULL REFERENCES activity_types(id),

                            review_id BIGINT NOT NULL REFERENCES reviews(id),

                            created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE notifications (
                               id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

                               user_id BIGINT NOT NULL REFERENCES users(id),

                               activity_id BIGINT NOT NULL REFERENCES activities(id),

                               message TEXT NOT NULL,
                               status VARCHAR(50) NOT NULL
);

CREATE TABLE tasteprofiles (
                               id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

                               user_id BIGINT UNIQUE REFERENCES users(id),

                               ibu_pref BIGINT,
                               abv_pref BIGINT,
                               srm_pref BIGINT,
                               og_pref  BIGINT,

                               fermentation_type BIGINT REFERENCES fermentation_types(id),

                               price BIGINT,

                               CONSTRAINT chk_tasteprofiles_price_non_negative CHECK (price IS NULL OR price >= 0),
                               CONSTRAINT chk_tasteprofiles_abv_range CHECK (abv_pref IS NULL OR (abv_pref >= 0 AND abv_pref <= 100)),
                               CONSTRAINT chk_tasteprofiles_ibu_non_negative CHECK (ibu_pref IS NULL OR ibu_pref >= 0),
                               CONSTRAINT chk_tasteprofiles_srm_non_negative CHECK (srm_pref IS NULL OR srm_pref >= 0),
                               CONSTRAINT chk_tasteprofiles_og_positive CHECK (og_pref IS NULL OR og_pref > 0)
);


CREATE TABLE review_user (
                             user_id BIGINT REFERENCES users(id),
                             review_id BIGINT REFERENCES reviews(id),
                             PRIMARY KEY (user_id, review_id)
);

CREATE TABLE recommendation (
                                user_id BIGINT REFERENCES users(id),
                                beer_id BIGINT REFERENCES beers(id),
                                PRIMARY KEY (user_id, beer_id)
);

CREATE TABLE favourite_beer (
                                user_id BIGINT REFERENCES users(id),
                                beer_id BIGINT REFERENCES beers(id),
                                PRIMARY KEY (user_id, beer_id)
);

CREATE TABLE subscribed_users (
                                  user_id BIGINT REFERENCES users(id),
                                  followed_user BIGINT REFERENCES users(id),
                                  PRIMARY KEY (user_id, followed_user)
);

CREATE TABLE notification_user (
                                   notification_id BIGINT REFERENCES notifications(id),
                                   user_id BIGINT REFERENCES users(id),
                                   PRIMARY KEY (notification_id, user_id)
);

ALTER TABLE beers
    ADD CONSTRAINT chk_beers_price_non_negative CHECK (price >= 0);

ALTER TABLE beers
    ADD CONSTRAINT chk_beers_volume_positive CHECK (volume > 0);

ALTER TABLE beers
    ADD CONSTRAINT chk_beers_abv_range CHECK (abv >= 0 AND abv <= 100);

ALTER TABLE beers
    ADD CONSTRAINT chk_beers_ibu_non_negative CHECK (ibu >= 0);

ALTER TABLE beers
    ADD CONSTRAINT chk_beers_srm_non_negative CHECK (srm >= 0);

ALTER TABLE beers
    ADD CONSTRAINT chk_beers_og_positive CHECK (og > 0);

CREATE INDEX IF NOT EXISTS idx_beers_ibu ON beers (ibu);
CREATE INDEX IF NOT EXISTS idx_beers_srm ON beers (srm);
CREATE INDEX IF NOT EXISTS idx_beers_abv ON beers (abv);
CREATE INDEX IF NOT EXISTS idx_beers_og  ON beers (og);
CREATE INDEX IF NOT EXISTS idx_beers_price ON beers (price);
CREATE INDEX IF NOT EXISTS idx_beers_fermentation_type ON beers (fermentation_type);

CREATE INDEX IF NOT EXISTS idx_tasteprofiles_fermentation_type ON tasteprofiles (fermentation_type);

CREATE INDEX IF NOT EXISTS idx_recommendation_user_id ON recommendation (user_id);
CREATE INDEX IF NOT EXISTS idx_recommendation_beer_id ON recommendation (beer_id);

CREATE INDEX IF NOT EXISTS idx_favourite_beer_user_id ON favourite_beer (user_id);
CREATE INDEX IF NOT EXISTS idx_favourite_beer_beer_id ON favourite_beer (beer_id);
