spring.application.name=pipivo

# Server
server.port=${SERVER_PORT:7777}

# DB
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5430/pipivodb}
spring.datasource.username=${DB_USERNAME:xax}
spring.datasource.password=${DB_PASSWORD:123}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.flyway.user=${DB_USERNAME:xax}
spring.flyway.password=${DB_PASSWORD:123}
spring.flyway.url=${DB_URL:jdbc:postgresql://localhost:5430/pipivodb}
spring.flyway.driver-class-name=org.postgresql.Driver
# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.id.new_generator_mappings=true
spring.jpa.defer-datasource-initialization=false
logging.level.org.flywaydb=DEBUG
logging.level.org.springframework.boot.autoconfigure.flyway=DEBUG
logging.level.org.springframework.boot.autoconfigure.condition=DEBUG


# Elasticsearch
spring.elasticsearch.uris=${ELASTIC_URL:http://localhost:9200}
spring.data.elasticsearch.repositories.enabled=true

# MinIO
minio.url=${MINIO_URL:http://localhost:9000}
minio.access.name=${MINIO_ACCESS_NAME:minioadmin}
minio.access.secret=${MINIO_ACCESS_SECRET:minioadmin123}
minio.bucket.name=${MINIO_BUCKET_NAME:pipivo}
beer.image.folder=${BEER_IMAGE_FOLDER:./beer_images}
avatar.image.folder=${AVATAR_IMAGE_FOLDER:./avatar_images}

# ReCaptcha
google.recaptcha.secret-key=${RECAPTCHA_SECRET_KEY:6LdUwesqAAAAAOwJbU0W-PsBViM332635efq4i5J}

# AOP
spring.aop.auto=false

# Logging
logging.level.root=${LOG_LEVEL_ROOT:INFO}
logging.level.com.itmo.is.lz.pipivo=${LOG_LEVEL_APP:DEBUG}
logging.level.org.springframework=ERROR
logging.level.org.hibernate=ERROR
logging.level.org.springframework.security=ERROR
logging.level.sun.rmi=ERROR
logging.level.javax.management=ERROR
logging.level.java.lang.ProcessBuilder=ERROR
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss.SSS} %-5level [%thread] %logger{36} traceId=%X{traceId} - %msg%n

spring.kafka.bootstrap-servers=localhost:9092

# Producer
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer

# Consumer
spring.kafka.consumer.group-id=taste-profile
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer
spring.kafka.consumer.properties.spring.json.trusted.packages=*


