spring.application.name=pipivo

# Server
server.port=${SERVER_PORT:7777}

# DB
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5430/pipivodb}
spring.datasource.username=${DB_USERNAME:xax}
spring.datasource.password=${DB_PASSWORD:123}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.id.new_generator_mappings=true

# Elasticsearch
spring.elasticsearch.uris=${ELASTIC_URL:http://localhost:9200}
spring.data.elasticsearch.repositories.enabled=true

# MinIO
minio.url=${MINIO_URL:http://localhost:9000}
minio.access.name=${MINIO_ACCESS_NAME:minioadmin}
minio.access.secret=${MINIO_ACCESS_SECRET:minioadmin123}
minio.bucket.name=${MINIO_BUCKET_NAME:pipivo}
beer.image.folder=${BEER_IMAGE_FOLDER:./beer_images}
avatar.image.folder=${AVATAR_IMAGE_FOLDER:./avatar_images}

# ReCaptcha
google.recaptcha.secret-key=${RECAPTCHA_SECRET_KEY:6LdUwesqAAAAAOwJbU0W-PsBViM332635efq4i5J}

# AOP
spring.aop.auto=false

# Logging
logging.level.root=${LOG_LEVEL_ROOT:INFO}
logging.level.com.itmo.is.lz.pipivo=${LOG_LEVEL_APP:DEBUG}
logging.level.org.springframework=ERROR
logging.level.org.hibernate=ERROR
logging.level.org.springframework.security=ERROR
logging.level.sun.rmi=ERROR
logging.level.javax.management=ERROR
logging.level.java.lang.ProcessBuilder=ERROR
